### ISSUE TITLE
How about swift 3 support ?

### ISSUE THREAD

**Issue by dongmai** [Clean-Swift/CleanStore#14]

**Comment by jakubpetrik** [comment]
I've converted project to Swift 3 here: https://github.com/Clean-Swift/CleanStore/pull/15.

**Comment by damianesteban** [comment]
@rayvinly Are you still actively maintaining this project?

**Comment by Gudmundr** [comment]
There are 2 active Swift 3 branches that must be reviewed and merged. Stay tuned :-)

Kind regards
Cristian Azov

**Comment by damianesteban** [comment]
Great.  Thank you.


On October 25, 2016 at 14:29:13, Cristian Azov (notifications@github.com)
wrote:

There are 2 active Swift 3 branches that must be reviewed and merged. Stay
tuned :-)

Kind regards
Cristian Azov

> On Oct 24, 2016, at 12:42 AM, Damian Esteban <notifications@github.com>
wrote:
>
> @rayvinly Are you still actively maintaining this project?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
>

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/Clean-Swift/CleanStore/issues/14#issuecomment-256126333>,
or mute the thread

**Comment by jejernig** [comment]
Did you fork it? Or is there an active branch that we can pull request to?

**Comment by basememara** [comment]
Pls close, `master` is now Swift 4.
